import miradorCanvasCurationsPlugin from './plugins/miradorCanvasCurationsPlugin';
import miradorCurationResourceImportPlugin from './plugins/miradorCurationResourceImportPlugin';
import miradorCurationSettingsPlugin from './plugins/miradorCurationSettingsPlugin';
import miradorCurationsOverlayPlugin from './plugins/miradorCurationsOverlayPlugin';
import miradorCurationTooltipsOverlayPlugin from './plugins/miradorCurationTooltipsOverlayPlugin';
import miradorWindowSideBarCurationButtonPlugin from './plugins/miradorWindowSideBarCurationButtonPlugin';
import miradorWindowSideBarCurationsPanelPlugin from './plugins/miradorWindowSideBarCurationsPanelPlugin';
export { miradorCanvasCurationsPlugin, miradorCurationResourceImportPlugin, miradorCurationSettingsPlugin, miradorCurationsOverlayPlugin, miradorCurationTooltipsOverlayPlugin, miradorWindowSideBarCurationsPanelPlugin, miradorWindowSideBarCurationButtonPlugin };
export default [miradorCanvasCurationsPlugin, miradorCurationResourceImportPlugin, miradorCurationSettingsPlugin, miradorCurationsOverlayPlugin, miradorCurationTooltipsOverlayPlugin, miradorWindowSideBarCurationsPanelPlugin, miradorWindowSideBarCurationButtonPlugin];